//! `corpus-tool attest-pack` — builds the derived attestation binary
//! artifact.
//!
//! Produces the `.bin` artifact `friction_packs::ATTESTATION` loads at
//! runtime: the bigram/skeleton membership tables pre-flattened into
//! sorted arrays a zero-copy view binary-searches, instead of re-parsed
//! from ~1.8 MB of TOML on every process start (see `friction_packs`'
//! `attestation` module docs for the exact byte layout and the measured
//! startup cost it removes).
//!
//! Deterministic and fully offline: the input is the vendored
//! `attestation-v1.toml` already checked into `crates/friction-packs/
//! packs/`, written by `corpus-tool attest`. This command hands its text
//! to [`friction_packs::pack_attestation_bin`] — which records the
//! TOML's sha256 in the artifact header, so a stale `.bin` (TOML
//! regenerated by `corpus-tool attest` or its `--calibrate-near-noop`
//! stage, this command not re-run) fails loudly in `friction-packs`' own
//! drift test instead of silently serving tables mined from an older
//! corpus. **Re-run this command after every `corpus-tool attest` run.**

use std::path::PathBuf;

use anyhow::Context as _;
use clap::Args as ClapArgs;

/// Arguments for `corpus-tool attest-pack`.
#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Path to the vendored `attestation-v1.toml` pack.
    #[arg(
        long,
        default_value = "crates/friction-packs/packs/attestation-v1.toml"
    )]
    pub attestation_toml: PathBuf,
    /// Path to write the derived binary artifact to.
    #[arg(long, default_value = "crates/friction-packs/packs/attestation-v1.bin")]
    pub out_bin: PathBuf,
}

/// Runs `attest-pack`: reads the TOML pack, flattens both membership
/// tables, writes the artifact.
///
/// # Errors
/// Returns an error if the TOML can't be read or doesn't parse as a
/// valid `attestation-v1` pack (see
/// [`friction_packs::AttestationPack::parse`]), or if the `.bin` can't
/// be written.
pub fn run(args: &Args) -> anyhow::Result<()> {
    let toml_text = std::fs::read_to_string(&args.attestation_toml)
        .with_context(|| format!("reading {}", args.attestation_toml.display()))?;
    let packed = friction_packs::pack_attestation_bin(&toml_text)
        .with_context(|| format!("packing {}", args.attestation_toml.display()))?;
    if let Some(parent) = args.out_bin.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&args.out_bin, &packed)
        .with_context(|| format!("writing {}", args.out_bin.display()))?;

    println!(
        "attest-pack: {} ({} bytes) -> {} ({} bytes)",
        args.attestation_toml.display(),
        toml_text.len(),
        args.out_bin.display(),
        packed.len(),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    /// Packing the vendored TOML twice is byte-identical — the same
    /// determinism pin `dms-pack` and `weights-pack` carry, at this
    /// command's own read-pack level over the real artifact.
    #[test]
    fn packing_the_vendored_toml_twice_is_byte_identical() {
        let repo_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("workspace root exists");
        let toml_text = std::fs::read_to_string(
            repo_root.join("crates/friction-packs/packs/attestation-v1.toml"),
        )
        .expect("vendored attestation-v1.toml exists");
        let first = friction_packs::pack_attestation_bin(&toml_text).expect("vendored pack packs");
        let second = friction_packs::pack_attestation_bin(&toml_text).expect("vendored pack packs");
        assert_eq!(first, second);
    }
}
