//! `corpus-tool dms-pack` — builds the derived DMS binary artifact.
//!
//! Produces the `.bin` artifact `friction_packs::DMS` loads at runtime:
//! every stream's suffix automaton pre-built and serialized flat, read
//! back as a zero-copy view instead of re-parsed and re-constructed on
//! every process start (see `friction_packs`' own `dms_bin` module docs
//! for the exact byte layout and the measured startup cost it removes).
//!
//! Deterministic and fully offline: the input is the vendored
//! `dms-index-en-v1.toml` already checked into `crates/friction-packs/
//! packs/`, written by `corpus-tool index`. This command hands its text
//! to [`friction_packs::pack_dms_index_bin`] — which records the TOML's
//! sha256 in the artifact header, so a stale `.bin` (TOML regenerated by
//! `corpus-tool index`, this command not re-run) fails loudly in
//! `friction-packs`' own drift test instead of silently serving automata
//! built from an older corpus. **Re-run this command after every
//! `corpus-tool index` run.**

use std::path::PathBuf;

use anyhow::Context as _;
use clap::Args as ClapArgs;

/// Arguments for `corpus-tool dms-pack`.
#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Path to the vendored `dms-index-en-v1.toml` pack.
    #[arg(
        long,
        default_value = "crates/friction-packs/packs/dms-index-en-v1.toml"
    )]
    pub dms_toml: PathBuf,
    /// Path to write the derived binary artifact to.
    #[arg(
        long,
        default_value = "crates/friction-packs/packs/dms-index-en-v1.bin"
    )]
    pub out_bin: PathBuf,
}

/// Runs `dms-pack`: reads the TOML pack, builds and serializes every
/// stream's automaton, writes the artifact.
///
/// # Errors
/// Returns an error if the TOML can't be read or doesn't parse as a
/// valid `dms-index-v1` pack (see [`friction_packs::DmsIndex::parse`]),
/// or if the `.bin` can't be written.
pub fn run(args: &Args) -> anyhow::Result<()> {
    let toml_text = std::fs::read_to_string(&args.dms_toml)
        .with_context(|| format!("reading {}", args.dms_toml.display()))?;
    let packed = friction_packs::pack_dms_index_bin(&toml_text)
        .with_context(|| format!("packing {}", args.dms_toml.display()))?;
    if let Some(parent) = args.out_bin.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&args.out_bin, &packed)
        .with_context(|| format!("writing {}", args.out_bin.display()))?;

    let view = friction_packs::DmsIndexView::parse(&packed)
        .expect("bytes this command just packed always parse");
    println!(
        "dms-pack: {} ({} bytes) -> {} ({} bytes), source sha256 {}",
        args.dms_toml.display(),
        toml_text.len(),
        args.out_bin.display(),
        packed.len(),
        view.source_sha256_hex(),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    /// Packing the vendored TOML twice is byte-identical — the same
    /// determinism pin `weights-pack` and `jargon-attest` carry, at this
    /// command's own read-pack level over the real artifact.
    #[test]
    fn packing_the_vendored_toml_twice_is_byte_identical() {
        let repo_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("workspace root exists");
        let toml_text = std::fs::read_to_string(
            repo_root.join("crates/friction-packs/packs/dms-index-en-v1.toml"),
        )
        .expect("vendored dms-index-en-v1.toml exists");
        let first = friction_packs::pack_dms_index_bin(&toml_text).expect("vendored pack packs");
        let second = friction_packs::pack_dms_index_bin(&toml_text).expect("vendored pack packs");
        assert_eq!(first, second);
    }
}
