//! Derived binary DMS artifact: the pre-built suffix automata
//! `packs/dms-index-en-v1.toml` describes, serialized flat so runtime never
//! builds them again.
//!
//! # Why this exists
//!
//! [`crate::DmsIndex::parse`] is the audited read side of the TOML pack
//! `corpus-tool index` writes, and stays the source of truth — but it
//! pays a real price on every process start: parsing ~2.5 MB of TOML and
//! then running [`crate::Sam`]'s reference `extend` loop over every
//! stream, allocating one `HashMap` per automaton state. That
//! construction was the whole of `friction`'s measured fixed startup
//! cost (~90 ms), dwarfing the actual work on README-sized documents.
//!
//! This module is the same cure the perceptron weights already received
//! (`friction-nlp`'s `weights_bin`, format version 2): do the expensive
//! construction **once, offline**, in `corpus-tool dms-pack`, and
//! serialize the finished automata in a layout the runtime can use as a
//! zero-copy view over the `include_bytes!`'d static: a handful of
//! slice splits at load, no per-state work at all.
//!
//! # Layout
//!
//! A fixed header, then little-endian sections. Every multi-byte field is
//! read via `from_le_bytes` on a byte slice — alignment-free by
//! construction, so no `unsafe` is ever needed (this workspace denies
//! `unsafe_code`).
//!
//! - **Header**: 8-byte magic `FRDMSIDX`, `u16` format version, 64-byte
//!   lowercase-hex sha256 of the source TOML this artifact was packed
//!   from. Recording the source sha lets a stale `.bin` (TOML
//!   regenerated by `corpus-tool index`, `dms-pack` not re-run) fail
//!   loudly in this crate's own drift test rather than silently serving
//!   automata built from an older corpus.
//! - **Vocab**: token count `n`; `n + 1` cumulative `u32` byte offsets
//!   into a string pool; the pool itself (`u32` length prefix); and a
//!   lookup table of token ids sorted by token text (`u32` count, then
//!   that many `u32` ids) for [`VocabView::id_of`]'s binary search.
//!   Duplicate texts (tolerated by [`crate::Vocab`], resolved
//!   first-id-wins) are collapsed to their first id at pack time, so the
//!   sorted table's texts are strictly increasing and the search is
//!   unambiguous.
//! - **Streams**: stream count, then per stream a `u32` tag (`0` =
//!   human, `1 + ModelFamily::ALL` position for a per-family stream,
//!   [`POOLED_MACHINE_TAG`] for the pooled machine stream — see below)
//!   and one serialized automaton: state count `s`; `s` `u32` `len`
//!   values; `s` `u32` suffix links ([`ROOT_LINK_SENTINEL`] for the
//!   root's `None`); `s + 1` cumulative `u32` transition offsets (CSR);
//!   then the transition array, 8 bytes per edge (`label: u32`,
//!   `target: u32`), sorted by label within each state so [`SamView`]
//!   can binary-search where [`crate::Sam`] hash-probes.
//!
//! # Format version 2: the pooled machine stream
//!
//! Version 2 adds exactly one more stream to the section above, tagged
//! [`POOLED_MACHINE_TAG`]: [`crate::DmsIndex::pooled_machine_sam`], every
//! present family stream's ids concatenated in fixed alphabetical order
//! with the document separator between streams (see that method's own
//! docs). The five per-family sections from version 1 are unchanged and
//! still written — kept for `family_sam`/`--family` compatibility: the
//! pooled stream is additive, not a replacement. A version-1 artifact (no
//! pooled section) is rejected by [`DmsIndexView::parse`] as a
//! [`DmsBinError::VersionMismatch`]; there is no reader that accepts
//! both, since every producer (`corpus-tool dms-pack`) and consumer (this
//! crate's embedded artifact) ship together.
//!
//! # Determinism
//!
//! [`pack_dms_index_bin`] is a pure function of the TOML text:
//! [`crate::Sam`]'s build is deterministic (documented on the type), the
//! only `HashMap` iteration is explicitly sorted
//! (`Sam::sorted_transitions`), the vocab's duplicate collapse follows
//! `BTreeMap` order, and streams are written human-first, then
//! [`ModelFamily::ALL`] order, then the pooled machine stream last:
//! packing the same TOML twice produces bit-identical bytes (pinned by
//! this module's own determinism test).
//!
//! # Equivalence
//!
//! [`SamView::matching_stats`] walks the identical automaton with the
//! identical reference control flow as [`crate::Sam::matching_stats`] —
//! only the transition lookup differs (binary search over a sorted CSR
//! slice instead of a `HashMap` probe), which cannot change which state
//! is reached. Parity is pinned by tests comparing both walks over the
//! same packs, and by the CLI's byte-identical fixture battery.

use crate::dms::{DmsIndex, ModelFamily, Sam};
use crate::{PackError, Sha256};

/// The 8-byte magic every DMS binary artifact starts with.
const MAGIC: [u8; 8] = *b"FRDMSIDX";

/// This module's on-disk format version: bumped if the layout above ever
/// changes shape. Bumped to `2` when [`POOLED_MACHINE_TAG`]'s stream was
/// added (see the module docs' "Format version 2" section).
const FORMAT_VERSION: u16 = 2;

/// The stream tag for [`crate::DmsIndex::pooled_machine_sam`] — one past
/// the last per-family tag (`1 + ModelFamily::ALL` position), so it never
/// collides with a real family's tag regardless of how many families a
/// pack defines. Written as a literal (not `1 + ModelFamily::ALL.len()
/// as u32`) to keep this a `usize`-cast-free `const`; the assertion right
/// below pins it against drift if [`ModelFamily::ALL`] ever grows.
const POOLED_MACHINE_TAG: u32 = 6;
const _: () = assert!(
    POOLED_MACHINE_TAG as usize == 1 + ModelFamily::ALL.len(),
    "POOLED_MACHINE_TAG must stay one past the last per-family tag"
);

/// A sha256 digest is recorded as lowercase hex (matching
/// [`Sha256`]'s `Display`), not raw bytes, so a hex dump of the header
/// stays human-legible — same choice as `friction-nlp`'s weight headers.
const SHA256_HEX_LEN: usize = 64;

/// The fixed-length prefix: magic + version + source sha256 hex.
const HEADER_LEN: usize = 8 + 2 + SHA256_HEX_LEN;

/// The `link` value serialized for the root state's `None` — no real
/// state index is ever `u32::MAX` (a real automaton of that size would
/// dwarf addressable memory long before).
const ROOT_LINK_SENTINEL: u32 = u32::MAX;

/// Bytes per serialized transition: `label: u32` + `target: u32`.
const TRANS_ENTRY_LEN: usize = 8;

/// Errors reading a DMS binary artifact.
///
/// Never expected for the vendored artifact (covered by this crate's own
/// round-trip and drift tests): only for corrupted or hand-edited input.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum DmsBinError {
    /// Shorter than the fixed header: not an artifact this module wrote.
    #[error("DMS artifact truncated: {len} byte(s), need at least {min}")]
    Truncated { len: usize, min: usize },
    /// The first 8 bytes are not `FRDMSIDX`.
    #[error("DMS artifact has an unrecognized magic")]
    BadMagic,
    /// The version field isn't [`FORMAT_VERSION`].
    #[error("DMS artifact format version {found} is unsupported (expected {expected})")]
    VersionMismatch { found: u16, expected: u16 },
    /// The sha256 field isn't valid UTF-8.
    #[error("DMS artifact's recorded sha256 is not valid UTF-8")]
    BadSha256,
    /// A section was structurally inconsistent (a length running past the
    /// end of the artifact, an unknown stream tag, ...).
    #[error("DMS artifact payload is malformed: {0}")]
    Malformed(&'static str),
}

// ---------------------------------------------------------------------
// Packing (build side — `corpus-tool dms-pack`).
// ---------------------------------------------------------------------

/// Packs `toml_text` (a `dms-index-v1` pack) into this module's binary
/// layout.
///
/// Parses it with [`DmsIndex::parse`], builds every stream's [`Sam`]
/// exactly as the runtime used to, and serializes the finished automata
/// with the source's sha256 recorded in the header.
///
/// # Errors
/// Returns [`PackError`] if `toml_text` is not a valid `dms-index-v1`
/// pack — see [`DmsIndex::parse`]. Serialization itself cannot fail.
pub fn pack_dms_index_bin(toml_text: &str) -> Result<Vec<u8>, PackError> {
    let index = DmsIndex::parse(toml_text)?;
    let sha_hex = Sha256::of_bytes(toml_text.as_bytes()).to_string();

    let mut out = Vec::new();
    out.extend_from_slice(&MAGIC);
    out.extend_from_slice(&FORMAT_VERSION.to_le_bytes());
    out.extend_from_slice(sha_hex.as_bytes());

    write_vocab(&mut out, &index);

    let mut streams: Vec<(u32, &Sam)> = std::iter::once((0u32, index.human_sam()))
        .chain(index.family_sams().map(|(family, sam)| {
            let position = ModelFamily::ALL
                .iter()
                .position(|&f| f == family)
                .expect("ModelFamily::ALL is exhaustive by definition");
            (u32_from(position + 1), sam)
        }))
        .collect();
    streams.push((POOLED_MACHINE_TAG, index.pooled_machine_sam()));
    write_u32(&mut out, u32_from(streams.len()));
    for (tag, sam) in streams {
        write_u32(&mut out, tag);
        write_sam(&mut out, sam);
    }
    Ok(out)
}

/// Serializes the vocab section: see the module docs for the layout.
fn write_vocab(out: &mut Vec<u8>, index: &DmsIndex) {
    let vocab = index.vocab();
    let n = vocab.len();
    write_u32(out, u32_from(n));

    let mut pool: Vec<u8> = Vec::new();
    let mut offsets: Vec<u32> = Vec::with_capacity(n + 1);
    offsets.push(0);
    for id in 0..n {
        let token = vocab
            .token_of(u32_from(id))
            .expect("every id below Vocab::len resolves");
        pool.extend_from_slice(token.as_bytes());
        offsets.push(u32_from(pool.len()));
    }
    for offset in &offsets {
        write_u32(out, *offset);
    }
    write_u32(out, u32_from(pool.len()));
    out.extend_from_slice(&pool);

    // First-id-wins duplicate collapse, in BTreeMap (byte-string) order —
    // exactly the resolution `Vocab::id_of` documents.
    let mut first_by_text: std::collections::BTreeMap<&str, u32> =
        std::collections::BTreeMap::new();
    for id in 0..n {
        let token = vocab
            .token_of(u32_from(id))
            .expect("every id below Vocab::len resolves");
        first_by_text.entry(token).or_insert_with(|| u32_from(id));
    }
    write_u32(out, u32_from(first_by_text.len()));
    for &id in first_by_text.values() {
        write_u32(out, id);
    }
}

/// Serializes one automaton: see the module docs for the layout.
fn write_sam(out: &mut Vec<u8>, sam: &Sam) {
    let state_count = sam.state_count();
    write_u32(out, u32_from(state_count));
    for s in 0..state_count {
        write_u32(out, sam.len_of(s));
    }
    for s in 0..state_count {
        write_u32(out, sam.link_of(s).unwrap_or(ROOT_LINK_SENTINEL));
    }

    let per_state: Vec<Vec<(u32, u32)>> = (0..state_count)
        .map(|s| sam.sorted_transitions(s))
        .collect();
    let mut cumulative: u32 = 0;
    write_u32(out, cumulative);
    for transitions in &per_state {
        cumulative += u32_from(transitions.len());
        write_u32(out, cumulative);
    }
    for transitions in &per_state {
        for &(label, target) in transitions {
            write_u32(out, label);
            write_u32(out, target);
        }
    }
}

/// Appends `value` little-endian.
fn write_u32(out: &mut Vec<u8>, value: u32) {
    out.extend_from_slice(&value.to_le_bytes());
}

/// `usize -> u32` with the one honest justification every count in this
/// artifact shares.
fn u32_from(value: usize) -> u32 {
    u32::try_from(value).expect("a DMS pack's counts stay far below u32::MAX")
}

// ---------------------------------------------------------------------
// Views (runtime side).
// ---------------------------------------------------------------------

/// Reads the little-endian `u32` at logical index `index` of a `u32`
/// array serialized as raw bytes.
fn u32_at(region: &[u8], index: usize) -> u32 {
    let start = index * 4;
    u32::from_le_bytes(
        region[start..start + 4]
            .try_into()
            .expect("caller-validated 4-byte slice"),
    )
}

/// A tiny forward-only cursor for [`DmsIndexView::parse`]'s sequential
/// section reads.
struct Cursor<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Cursor<'a> {
    const fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, pos: 0 }
    }

    fn read_u32(&mut self) -> Result<u32, DmsBinError> {
        let slice = self.take(4)?;
        Ok(u32::from_le_bytes(
            slice.try_into().expect("checked 4-byte slice"),
        ))
    }

    fn take(&mut self, len: usize) -> Result<&'a [u8], DmsBinError> {
        let end = self
            .pos
            .checked_add(len)
            .filter(|&end| end <= self.bytes.len())
            .ok_or(DmsBinError::Malformed(
                "section ran past the end of the artifact",
            ))?;
        let slice = &self.bytes[self.pos..end];
        self.pos = end;
        Ok(slice)
    }

    /// Takes a `u32`-array region of `count` logical entries.
    fn take_u32s(&mut self, count: usize) -> Result<&'a [u8], DmsBinError> {
        self.take(count * 4)
    }

    const fn is_exhausted(&self) -> bool {
        self.pos == self.bytes.len()
    }
}

/// Zero-copy view over the serialized vocab: [`crate::Vocab`]'s exact
/// lookup surface, over borrowed bytes.
#[derive(Debug, Clone, Copy)]
pub struct VocabView<'a> {
    count: u32,
    /// `count + 1` cumulative byte offsets into `pool`.
    offsets: &'a [u8],
    pool: &'a [u8],
    /// Token ids sorted by token text, duplicates already collapsed.
    sorted_count: u32,
    sorted_ids: &'a [u8],
}

impl<'a> VocabView<'a> {
    /// The token text for `id`, as bytes — the comparison key
    /// [`Self::id_of`]'s binary search probes with.
    fn token_bytes(&self, id: u32) -> &'a [u8] {
        let start = u32_at(self.offsets, id as usize) as usize;
        let end = u32_at(self.offsets, id as usize + 1) as usize;
        &self.pool[start..end]
    }

    /// The id for `token`'s exact text, or `None` if out-of-vocab —
    /// [`crate::Vocab::id_of`]'s contract, including first-id-wins for
    /// duplicate texts (collapsed at pack time).
    #[must_use]
    pub fn id_of(&self, token: &str) -> Option<u32> {
        let key = token.as_bytes();
        let mut lo: u32 = 0;
        let mut hi: u32 = self.sorted_count;
        while lo < hi {
            let mid = lo + (hi - lo) / 2;
            let id = u32_at(self.sorted_ids, mid as usize);
            match self.token_bytes(id).cmp(key) {
                std::cmp::Ordering::Less => lo = mid + 1,
                std::cmp::Ordering::Greater => hi = mid,
                std::cmp::Ordering::Equal => return Some(id),
            }
        }
        None
    }

    /// The text for `id`, or `None` if `id` is not a valid id —
    /// [`crate::Vocab::token_of`]'s contract.
    #[must_use]
    pub fn token_of(&self, id: u32) -> Option<&'a str> {
        (id < self.count).then(|| {
            std::str::from_utf8(self.token_bytes(id))
                .expect("pack side wrote every token from a &str")
        })
    }

    /// The number of token ids (including the reserved unused id `0`).
    #[must_use]
    pub const fn len(&self) -> usize {
        self.count as usize
    }

    /// `true` if this vocab defines no token ids at all.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.count == 0
    }
}

/// Zero-copy view over one serialized suffix automaton:
/// [`crate::Sam::matching_stats`]'s exact walk, over borrowed bytes.
#[derive(Debug, Clone, Copy)]
pub struct SamView<'a> {
    lens: &'a [u8],
    links: &'a [u8],
    /// `state_count + 1` cumulative transition counts (CSR).
    trans_offsets: &'a [u8],
    /// [`TRANS_ENTRY_LEN`]-byte `(label, target)` pairs, label-sorted
    /// within each state.
    trans: &'a [u8],
}

impl SamView<'_> {
    /// State `s`'s outgoing transition on `label`, or `None` — the
    /// binary-search counterpart of [`crate::Sam`]'s `next[v].get(&c)`.
    fn transition(&self, state: u32, label: u32) -> Option<u32> {
        let mut lo = u32_at(self.trans_offsets, state as usize);
        let mut hi = u32_at(self.trans_offsets, state as usize + 1);
        while lo < hi {
            let mid = lo + (hi - lo) / 2;
            let entry = mid as usize * TRANS_ENTRY_LEN;
            let entry_label = u32::from_le_bytes(
                self.trans[entry..entry + 4]
                    .try_into()
                    .expect("4-byte slice"),
            );
            match entry_label.cmp(&label) {
                std::cmp::Ordering::Less => lo = mid + 1,
                std::cmp::Ordering::Greater => hi = mid,
                std::cmp::Ordering::Equal => {
                    return Some(u32::from_le_bytes(
                        self.trans[entry + 4..entry + 8]
                            .try_into()
                            .expect("4-byte slice"),
                    ));
                }
            }
        }
        None
    }

    /// State `s`'s `len` value.
    fn len_of(&self, state: u32) -> u32 {
        u32_at(self.lens, state as usize)
    }

    /// State `s`'s suffix link (`None` only for the root).
    fn link_of(&self, state: u32) -> Option<u32> {
        let raw = u32_at(self.links, state as usize);
        (raw != ROOT_LINK_SENTINEL).then_some(raw)
    }

    /// The longest match ENDING at each position of `query` — the same
    /// control flow as [`crate::Sam::matching_stats`], line for line (see
    /// that method's docs for the walk's semantics and the `None`
    /// out-of-vocab sentinel); only the transition lookup mechanism
    /// differs.
    #[must_use]
    pub fn matching_stats(&self, query: &[Option<u32>]) -> Vec<u32> {
        let mut v: u32 = 0;
        let mut l: u32 = 0;
        let mut out = Vec::with_capacity(query.len());

        for &c in query {
            let direct = c.and_then(|id| self.transition(v, id));
            if let Some(next_v) = direct {
                v = next_v;
                l += 1;
            } else {
                while v != 0 {
                    let has_transition = c.is_some_and(|id| self.transition(v, id).is_some());
                    if has_transition {
                        break;
                    }
                    v = self
                        .link_of(v)
                        .expect("every non-root state has a link, by construction in Sam::extend");
                    l = self.len_of(v);
                }
                let landed = c.and_then(|id| self.transition(v, id));
                if let Some(next_v) = landed {
                    v = next_v;
                    l += 1;
                } else {
                    v = 0;
                    l = 0;
                }
            }
            out.push(l);
        }
        out
    }
}

/// Zero-copy view over a whole serialized DMS index:
/// [`crate::DmsIndex`]'s exact query surface, over borrowed bytes —
/// what [`crate::DMS`] now exposes at runtime.
#[derive(Debug, Clone, Copy)]
pub struct DmsIndexView<'a> {
    vocab: VocabView<'a>,
    human: SamView<'a>,
    families: [Option<SamView<'a>>; 5],
    pooled_machine: SamView<'a>,
    source_sha256_hex: &'a str,
}

impl<'a> DmsIndexView<'a> {
    /// Parses a [`pack_dms_index_bin`]-written artifact into a view:
    /// header validation plus section slicing, no per-state work.
    ///
    /// # Errors
    /// Any [`DmsBinError`] variant: see each variant's own docs. Never
    /// expected for the vendored embedded artifact.
    pub fn parse(bytes: &'a [u8]) -> Result<Self, DmsBinError> {
        if bytes.len() < HEADER_LEN {
            return Err(DmsBinError::Truncated {
                len: bytes.len(),
                min: HEADER_LEN,
            });
        }
        if bytes[..8] != MAGIC {
            return Err(DmsBinError::BadMagic);
        }
        let version = u16::from_le_bytes(bytes[8..10].try_into().expect("2-byte slice"));
        if version != FORMAT_VERSION {
            return Err(DmsBinError::VersionMismatch {
                found: version,
                expected: FORMAT_VERSION,
            });
        }
        let source_sha256_hex =
            std::str::from_utf8(&bytes[10..HEADER_LEN]).map_err(|_| DmsBinError::BadSha256)?;

        let mut cursor = Cursor::new(&bytes[HEADER_LEN..]);
        let vocab = Self::parse_vocab(&mut cursor)?;

        let stream_count = cursor.read_u32()?;
        let mut human: Option<SamView<'a>> = None;
        let mut families: [Option<SamView<'a>>; 5] = [None; 5];
        let mut pooled_machine: Option<SamView<'a>> = None;
        for _ in 0..stream_count {
            let tag = cursor.read_u32()?;
            let sam = Self::parse_sam(&mut cursor)?;
            match tag {
                0 => human = Some(sam),
                POOLED_MACHINE_TAG => pooled_machine = Some(sam),
                t if (t as usize) <= ModelFamily::ALL.len() => {
                    families[t as usize - 1] = Some(sam);
                }
                _ => return Err(DmsBinError::Malformed("unknown stream tag")),
            }
        }
        if !cursor.is_exhausted() {
            return Err(DmsBinError::Malformed("trailing bytes after last stream"));
        }
        let human = human.ok_or(DmsBinError::Malformed("missing human stream"))?;
        let pooled_machine =
            pooled_machine.ok_or(DmsBinError::Malformed("missing pooled machine stream"))?;
        Ok(Self {
            vocab,
            human,
            families,
            pooled_machine,
            source_sha256_hex,
        })
    }

    /// Slices the vocab section — [`write_vocab`]'s exact read-side
    /// counterpart.
    fn parse_vocab(cursor: &mut Cursor<'a>) -> Result<VocabView<'a>, DmsBinError> {
        let count = cursor.read_u32()?;
        let offsets = cursor.take_u32s(count as usize + 1)?;
        let pool_len = cursor.read_u32()?;
        if u32_at(offsets, count as usize) != pool_len {
            return Err(DmsBinError::Malformed(
                "vocab's final offset disagrees with its pool length",
            ));
        }
        let pool = cursor.take(pool_len as usize)?;
        let sorted_count = cursor.read_u32()?;
        if sorted_count > count {
            return Err(DmsBinError::Malformed(
                "vocab's sorted lookup table is larger than the vocab itself",
            ));
        }
        let sorted_ids = cursor.take_u32s(sorted_count as usize)?;
        Ok(VocabView {
            count,
            offsets,
            pool,
            sorted_count,
            sorted_ids,
        })
    }

    /// Slices one automaton — [`write_sam`]'s exact read-side counterpart.
    fn parse_sam(cursor: &mut Cursor<'a>) -> Result<SamView<'a>, DmsBinError> {
        let state_count = cursor.read_u32()?;
        if state_count == 0 {
            return Err(DmsBinError::Malformed(
                "an automaton always has at least its root state",
            ));
        }
        let lens = cursor.take_u32s(state_count as usize)?;
        let links = cursor.take_u32s(state_count as usize)?;
        let trans_offsets = cursor.take_u32s(state_count as usize + 1)?;
        let trans_count = u32_at(trans_offsets, state_count as usize);
        let trans = cursor.take(trans_count as usize * TRANS_ENTRY_LEN)?;
        Ok(SamView {
            lens,
            links,
            trans_offsets,
            trans,
        })
    }

    /// This pack's shared token vocabulary.
    #[must_use]
    pub const fn vocab(&self) -> VocabView<'a> {
        self.vocab
    }

    /// The human-corpus suffix automaton.
    #[must_use]
    pub const fn human_sam(&self) -> SamView<'a> {
        self.human
    }

    /// The suffix automaton for `family`, or `None` if this pack defines
    /// no stream for that family. Kept for `family_sam`/`--family`
    /// compatibility; the runtime detection pass reads
    /// [`Self::pooled_machine_sam`] instead.
    #[must_use]
    pub fn family_sam(&self, family: ModelFamily) -> Option<SamView<'a>> {
        let position = ModelFamily::ALL
            .iter()
            .position(|&f| f == family)
            .expect("ModelFamily::ALL is exhaustive by definition");
        self.families[position]
    }

    /// The pooled machine-side automaton — every family stream this pack
    /// defines, concatenated in fixed alphabetical order with the
    /// document separator between streams (see
    /// [`crate::DmsIndex::pooled_machine_sam`]'s own docs for why). The
    /// single stream `friction-match`'s runtime detection pass scans
    /// against; family attribution is no longer surfaced.
    #[must_use]
    pub const fn pooled_machine_sam(&self) -> SamView<'a> {
        self.pooled_machine
    }

    /// The lowercase-hex sha256 of the source TOML this artifact was
    /// packed from, as recorded in its header.
    #[must_use]
    pub const fn source_sha256_hex(&self) -> &'a str {
        self.source_sha256_hex
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_PACK: &str = r#"
        [pack]
        version = "dms-index-v1"

        [vocab]
        tokens = ["<unused-0>", "the", "quick", "fox", "the"]

        [streams.human]
        ids = "1,2,3,2,3"

        [streams.qwen]
        ids = "2,3,1"

        [streams.claude]
        ids = "3,1,2,1"
    "#;

    fn packed_sample() -> Vec<u8> {
        pack_dms_index_bin(SAMPLE_PACK).expect("sample pack packs")
    }

    #[test]
    fn pack_is_deterministic() {
        assert_eq!(packed_sample(), packed_sample());
    }

    #[test]
    fn header_records_the_source_sha256() {
        let bytes = packed_sample();
        let view = DmsIndexView::parse(&bytes).expect("packed sample parses");
        assert_eq!(
            view.source_sha256_hex(),
            Sha256::of_bytes(SAMPLE_PACK.as_bytes()).to_string()
        );
    }

    #[test]
    fn vocab_view_matches_owned_vocab_including_duplicate_resolution() {
        let bytes = packed_sample();
        let view = DmsIndexView::parse(&bytes).expect("packed sample parses");
        let owned = DmsIndex::parse(SAMPLE_PACK).expect("sample pack parses");

        assert_eq!(view.vocab().len(), owned.vocab().len());
        assert!(!view.vocab().is_empty());
        // "the" appears at ids 1 and 4; both sides must resolve to 1.
        assert_eq!(view.vocab().id_of("the"), Some(1));
        assert_eq!(view.vocab().id_of("the"), owned.vocab().id_of("the"));
        for token in ["<unused-0>", "quick", "fox", "absent"] {
            assert_eq!(
                view.vocab().id_of(token),
                owned.vocab().id_of(token),
                "{token:?}"
            );
        }
        for id in 0..=5u32 {
            assert_eq!(
                view.vocab().token_of(id),
                owned.vocab().token_of(id),
                "id {id}"
            );
        }
    }

    /// The heart of the whole module: for every stream, the view's walk
    /// and the owned reference walk must agree on every query — including
    /// out-of-vocab `None`s, unseen ids, and resets.
    #[test]
    fn sam_view_matching_stats_matches_owned_sam_on_every_stream() {
        let bytes = packed_sample();
        let view = DmsIndexView::parse(&bytes).expect("packed sample parses");
        let owned = DmsIndex::parse(SAMPLE_PACK).expect("sample pack parses");

        let queries: Vec<Vec<Option<u32>>> = vec![
            vec![Some(1), Some(2), Some(3), Some(2), Some(3)],
            vec![Some(2), Some(1), Some(2), Some(3), Some(1)],
            vec![Some(1), Some(2), None, Some(2), Some(3)],
            vec![Some(9), Some(9), Some(1)],
            vec![None, None],
            vec![],
        ];
        for query in &queries {
            assert_eq!(
                view.human_sam().matching_stats(query),
                owned.human_sam().matching_stats(query),
                "human stream, query {query:?}"
            );
            for family in ModelFamily::ALL {
                match (view.family_sam(family), owned.family_sam(family)) {
                    (Some(view_sam), Some(owned_sam)) => assert_eq!(
                        view_sam.matching_stats(query),
                        owned_sam.matching_stats(query),
                        "{family} stream, query {query:?}"
                    ),
                    (None, None) => {}
                    (view_side, owned_side) => panic!(
                        "family presence disagrees for {family}: view {} vs owned {}",
                        view_side.is_some(),
                        owned_side.is_some()
                    ),
                }
            }
        }
    }

    /// The pooled machine stream's view walk agrees with the owned
    /// reference walk on every query — the same parity contract
    /// [`sam_view_matching_stats_matches_owned_sam_on_every_stream`] pins
    /// for the human/per-family streams, extended to the new format-2
    /// section.
    #[test]
    fn pooled_machine_sam_view_matches_owned_pooled_machine_sam() {
        let bytes = packed_sample();
        let view = DmsIndexView::parse(&bytes).expect("packed sample parses");
        let owned = DmsIndex::parse(SAMPLE_PACK).expect("sample pack parses");

        let queries: Vec<Vec<Option<u32>>> = vec![
            vec![Some(1), Some(2), Some(3), Some(2), Some(3)],
            vec![Some(2), Some(1), Some(2), Some(3), Some(1)],
            vec![Some(1), Some(2), None, Some(2), Some(3)],
            vec![Some(9), Some(9), Some(1)],
            vec![None, None],
            vec![],
        ];
        for query in &queries {
            assert_eq!(
                view.pooled_machine_sam().matching_stats(query),
                owned.pooled_machine_sam().matching_stats(query),
                "pooled machine stream, query {query:?}"
            );
        }
    }

    #[test]
    fn family_presence_mirrors_the_source_pack() {
        let bytes = packed_sample();
        let view = DmsIndexView::parse(&bytes).expect("packed sample parses");
        assert!(view.family_sam(ModelFamily::Qwen).is_some());
        assert!(view.family_sam(ModelFamily::Claude).is_some());
        assert!(view.family_sam(ModelFamily::Gemma).is_none());
        assert!(view.family_sam(ModelFamily::Llama).is_none());
        assert!(view.family_sam(ModelFamily::Granite).is_none());
    }

    #[test]
    fn parse_rejects_truncated_input() {
        assert!(matches!(
            DmsIndexView::parse(b"short"),
            Err(DmsBinError::Truncated { .. })
        ));
    }

    #[test]
    fn parse_rejects_wrong_magic() {
        let mut bytes = packed_sample();
        bytes[0] = b'X';
        assert!(matches!(
            DmsIndexView::parse(&bytes),
            Err(DmsBinError::BadMagic)
        ));
    }

    #[test]
    fn parse_rejects_wrong_version() {
        let mut bytes = packed_sample();
        bytes[8..10].copy_from_slice(&99u16.to_le_bytes());
        assert!(matches!(
            DmsIndexView::parse(&bytes),
            Err(DmsBinError::VersionMismatch { found: 99, .. })
        ));
    }

    #[test]
    fn parse_rejects_trailing_bytes() {
        let mut bytes = packed_sample();
        bytes.push(0);
        assert!(matches!(
            DmsIndexView::parse(&bytes),
            Err(DmsBinError::Malformed(_))
        ));
    }

    #[test]
    fn parse_rejects_a_truncated_payload() {
        let bytes = packed_sample();
        assert!(DmsIndexView::parse(&bytes[..bytes.len() - 4]).is_err());
    }
}
