//! [`EnvelopePack`]: a parsed `corpus-tool envelope` pack — per-`(genre,
//! metric)` human percentile bands — as an in-memory lookup table.
//!
//! `corpus-tool envelope` estimates, from the train split, a `[lo, hi]`
//! human percentile band for every `(genre, metric)` pair and writes it
//! to a versioned TOML file (`packs/envelope-v2.toml` in this crate,
//! embedded at build time exactly like `registry.toml`). This module is
//! the read side: parsing that file's shape back into a lookup a rule
//! engine can query at runtime.
//!
//! The same TOML file also carries a `direction` (which class runs
//! higher, informational only) and an `include` flag per `(genre,
//! metric)` — whether that metric counts toward a combined
//! out-of-envelope score at all. [`EnvelopePack`] keeps `include`
//! alongside each `[lo, hi]` band (exposed via [`EnvelopePack::
//! combined_score`]) but not `direction`, which no consumer of this pack
//! needs today; it's present in the source TOML but simply never named in
//! [`RawBand`], so serde ignores it rather than this module duplicating
//! data it has no use for.

use std::collections::BTreeMap;
use std::sync::LazyLock;

use friction_core::{Envelope, MetricVector};
use serde::Deserialize;

use crate::PackError;

/// The embedded, current envelope pack (`envelope-v2`), generated by
/// `corpus-tool envelope` from the train split and vendored into this
/// crate the same way `registry.toml` is.
const ENVELOPE_V2_TOML: &str = include_str!("../packs/envelope-v2.toml");

/// The parsed, embedded `envelope-v2` pack, parsed once and reused for
/// the life of the process.
///
/// # Panics
/// Panics if the embedded `envelope-v2.toml` fails to parse — a bug in
/// this crate's own vendored data (covered by this module's tests), not a
/// condition any caller can recover from by retrying.
pub static ENVELOPE_V2: LazyLock<EnvelopePack> = LazyLock::new(|| {
    EnvelopePack::parse(ENVELOPE_V2_TOML)
        .expect("embedded envelope-v2.toml must parse: see this crate's envelope tests")
});

/// The TOML shape of one `[<genre>.<metric>]` table, before the
/// `lo <= hi` and finiteness check. `direction`/`train_auc` also appear
/// in the file but are not named here — see the module docs.
#[derive(Debug, Deserialize)]
struct RawBand {
    lo: f64,
    hi: f64,
    #[serde(default = "default_include")]
    include: bool,
}

/// `RawBand::include`'s default when a `[<genre>.<metric>]` table omits
/// it (e.g. a hand-written test fixture): counted toward the combined
/// score by default, matching `corpus-tool envelope`'s own "include
/// unless a train-internal AUC says otherwise" framing.
const fn default_include() -> bool {
    true
}

/// One `(genre, metric)` band plus whether it counts toward
/// [`EnvelopePack::combined_score`].
#[derive(Debug, Clone, Copy)]
struct Band {
    envelope: Envelope,
    include: bool,
}

/// A parsed envelope pack: every `(genre, metric)` human percentile band
/// it defines, keyed for lookup.
#[derive(Debug, Clone, Default)]
pub struct EnvelopePack {
    genres: BTreeMap<Box<str>, BTreeMap<Box<str>, Band>>,
}

impl EnvelopePack {
    /// Parses a pack from its TOML text: a `[pack]` metadata table
    /// (ignored here — see the module docs) plus one `[<genre>.<metric>]`
    /// table per band.
    ///
    /// # Errors
    /// Returns [`PackError::Toml`] if `toml` is not valid TOML or a
    /// `[<genre>.<metric>]` table doesn't have `lo`/`hi` numeric fields,
    /// and [`PackError::InvalidBand`] if a parsed band has `lo > hi` or a
    /// non-finite bound.
    pub fn parse(toml: &str) -> Result<Self, PackError> {
        let root: toml::Table = toml.parse().map_err(PackError::from)?;
        let mut genres: BTreeMap<Box<str>, BTreeMap<Box<str>, Band>> = BTreeMap::new();

        for (top_key, top_value) in &root {
            if top_key == "pack" {
                continue;
            }
            let Some(metrics) = top_value.as_table() else {
                continue;
            };
            let mut bands: BTreeMap<Box<str>, Band> = BTreeMap::new();
            for (metric_key, band_value) in metrics {
                let raw: RawBand = band_value.clone().try_into()?;
                if !raw.lo.is_finite() || !raw.hi.is_finite() || raw.lo > raw.hi {
                    return Err(PackError::InvalidBand {
                        genre: top_key.clone(),
                        metric: metric_key.clone(),
                        lo: raw.lo,
                        hi: raw.hi,
                    });
                }
                bands.insert(
                    metric_key.as_str().into(),
                    Band {
                        envelope: Envelope::new(raw.lo, raw.hi),
                        include: raw.include,
                    },
                );
            }
            genres.insert(top_key.as_str().into(), bands);
        }

        Ok(Self { genres })
    }

    /// The `[lo, hi]` band for `(genre, metric)`, or `None` if this pack
    /// has no band for that pair (unrecognized genre or metric name, or a
    /// genre with no train-split human data for that metric).
    #[must_use]
    pub fn band(&self, genre: &str, metric: &str) -> Option<Envelope> {
        Some(self.genres.get(genre)?.get(metric)?.envelope)
    }

    /// Every genre name this pack has at least one band for, in sorted
    /// order.
    #[must_use]
    pub fn genres(&self) -> Vec<&str> {
        self.genres.keys().map(AsRef::as_ref).collect()
    }

    /// The mean, over `metrics`'s fields this pack marks `include: true`
    /// for `genre`, of that field's normalized directional exceedance
    /// beyond its `[lo, hi]` band (see [`exceedance`]) — the same
    /// "combined out-of-envelope score" `corpus-tool separate` reports,
    /// `0.0` meaning every included metric sits inside its band.
    ///
    /// `None` if this pack has no band at all for `genre` (never called
    /// for any of `metrics`'s fields), or if every field it does have a
    /// band for is excluded (no basis for a score).
    #[must_use]
    pub fn combined_score(&self, genre: &str, metrics: &MetricVector) -> Option<f64> {
        let bands = self.genres.get(genre)?;
        let mut included_total = 0.0;
        let mut included_count = 0usize;
        for (name, value) in metrics.named_values() {
            let Some(band) = bands.get(name) else {
                continue;
            };
            if !band.include {
                continue;
            }
            included_count += 1;
            included_total += exceedance(value, band.envelope);
        }
        if included_count == 0 {
            return None;
        }
        #[allow(clippy::cast_precision_loss)]
        Some(included_total / included_count as f64)
    }
}

/// Normalized directional exceedance of `value` beyond `envelope`.
///
/// `0.0` if `value` falls inside `envelope`'s `[lo, hi]` band (inclusive
/// on both ends); otherwise the distance from `value` to the *nearer*
/// band edge, divided by the band width, capped at `1.0`. A zero-width
/// band (`lo == hi`) treats any miss as full (`1.0`) exceedance rather
/// than dividing by zero.
#[must_use]
pub fn exceedance(value: f64, envelope: Envelope) -> f64 {
    let width = envelope.hi - envelope.lo;
    if value < envelope.lo {
        if width <= 0.0 {
            1.0
        } else {
            ((envelope.lo - value) / width).min(1.0)
        }
    } else if value > envelope.hi {
        if width <= 0.0 {
            1.0
        } else {
            ((value - envelope.hi) / width).min(1.0)
        }
    } else {
        0.0
    }
}

#[cfg(test)]
// Comparisons below are against exact hand-computed literals (e.g. a
// value exactly inside a band is exactly `0.0` exceedance) — exact
// equality is the correct check there; the one case involving real
// division (`combined_score_matches_hand_computed_mean_exceedance`) uses
// an explicit epsilon check instead of `assert_eq!`.
#[allow(clippy::float_cmp)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
        [pack]
        version = "test"

        [blog.contraction_ratio]
        lo = 0.1
        hi = 0.9
        direction = "llm higher"
        include = true
        train_auc = 0.87

        [blog.em_dash_density]
        lo = 0.0
        hi = 5.0

        [docs.contraction_ratio]
        lo = 0.0
        hi = 0.5
    "#;

    /// A well-formed sample pack parses and looks up bands for every
    /// `(genre, metric)` pair it defines, extra fields (`direction`,
    /// `include`, `train_auc`) simply ignored.
    #[test]
    fn parse_looks_up_known_bands() {
        let pack = EnvelopePack::parse(SAMPLE).expect("sample pack parses");
        assert_eq!(
            pack.band("blog", "contraction_ratio"),
            Some(Envelope::new(0.1, 0.9))
        );
        assert_eq!(
            pack.band("blog", "em_dash_density"),
            Some(Envelope::new(0.0, 5.0))
        );
        assert_eq!(
            pack.band("docs", "contraction_ratio"),
            Some(Envelope::new(0.0, 0.5))
        );
    }

    /// An unrecognized genre or metric returns `None`, never a panic.
    #[test]
    fn parse_returns_none_for_unknown_genre_or_metric() {
        let pack = EnvelopePack::parse(SAMPLE).expect("sample pack parses");
        assert_eq!(pack.band("blog", "not_a_metric"), None);
        assert_eq!(pack.band("not_a_genre", "contraction_ratio"), None);
    }

    /// The `[pack]` metadata table itself is never mistaken for a genre.
    #[test]
    fn parse_skips_the_pack_metadata_table() {
        let pack = EnvelopePack::parse(SAMPLE).expect("sample pack parses");
        assert!(pack.band("pack", "version").is_none());
        assert_eq!(pack.genres(), vec!["blog", "docs"]);
    }

    /// Malformed TOML is a parse error, not a panic.
    #[test]
    fn parse_rejects_malformed_toml() {
        assert!(EnvelopePack::parse("not [ valid toml").is_err());
    }

    /// A band with `lo > hi` is rejected.
    #[test]
    fn parse_rejects_inverted_band() {
        let bad = r"
            [blog.some_metric]
            lo = 5.0
            hi = 1.0
        ";
        let err = EnvelopePack::parse(bad).expect_err("inverted band must be rejected");
        assert!(matches!(err, PackError::InvalidBand { .. }));
    }

    /// A band missing `lo`/`hi` (wrong shape) is a parse error.
    #[test]
    fn parse_rejects_band_missing_fields() {
        let bad = r#"
            [blog.some_metric]
            note = "oops, no lo/hi"
        "#;
        assert!(EnvelopePack::parse(bad).is_err());
    }

    /// The embedded `envelope-v2.toml` this crate ships parses cleanly
    /// and has bands for the five frozen v1 genres.
    #[test]
    fn embedded_envelope_v2_parses_and_covers_all_genres() {
        let pack = &*ENVELOPE_V2;
        for genre in ["blog", "docs", "email", "forum", "readme"] {
            assert!(
                pack.band(genre, "contraction_ratio").is_some(),
                "expected a contraction_ratio band for genre {genre:?}"
            );
        }
    }

    /// Hand-computed: inside the band is zero exceedance; below `lo` or
    /// above `hi` is the normalized distance to the nearer edge, capped
    /// at `1.0`.
    #[test]
    fn exceedance_hand_computed() {
        let band = Envelope::new(10.0, 20.0);
        assert_eq!(exceedance(15.0, band), 0.0);
        assert_eq!(exceedance(10.0, band), 0.0);
        assert_eq!(exceedance(20.0, band), 0.0);
        // 5.0 below lo, width 10.0 -> 5.0 / 10.0 = 0.5.
        assert_eq!(exceedance(5.0, band), 0.5);
        // 30.0 above hi (10.0 over), width 10.0 -> 10.0 / 10.0 = 1.0.
        assert_eq!(exceedance(30.0, band), 1.0);
        // 100.0 above hi would be 8.0x width, capped at 1.0.
        assert_eq!(exceedance(100.0, band), 1.0);
    }

    /// A zero-width band treats any miss as full exceedance rather than
    /// dividing by zero.
    #[test]
    fn exceedance_zero_width_band_is_binary() {
        let band = Envelope::new(5.0, 5.0);
        assert_eq!(exceedance(5.0, band), 0.0);
        assert_eq!(exceedance(4.0, band), 1.0);
        assert_eq!(exceedance(6.0, band), 1.0);
    }

    fn metrics_with(contraction_ratio: f64, em_dash_density: f64) -> MetricVector {
        MetricVector {
            contraction_ratio,
            em_dash_density,
            ..MetricVector::default()
        }
    }

    /// `combined_score` averages exceedance only over included metrics
    /// with a band for the genre — hand-computed: `contraction_ratio` at
    /// 0.5 sits inside `[0.1, 0.9]` (exceedance 0.0), `em_dash_density`
    /// at 6.0 sits 1.0 over a `[0.0, 5.0]` band with width 5.0
    /// (exceedance `1.0/5.0 = 0.2`); mean of `[0.0, 0.2]` is `0.1`.
    #[test]
    fn combined_score_matches_hand_computed_mean_exceedance() {
        let pack = EnvelopePack::parse(SAMPLE).expect("sample pack parses");
        let metrics = metrics_with(0.5, 6.0);
        let score = pack
            .combined_score("blog", &metrics)
            .expect("blog has bands for both fields");
        assert!((score - 0.1).abs() < 1e-9, "expected ~0.1, got {score}");
    }

    /// A metric this pack marks `include: false` for a genre never
    /// contributes to that genre's combined score.
    #[test]
    fn combined_score_skips_excluded_metrics() {
        let excluded = r"
            [blog.contraction_ratio]
            lo = 0.1
            hi = 0.9
            include = false

            [blog.em_dash_density]
            lo = 0.0
            hi = 5.0
            include = true
        ";
        let pack = EnvelopePack::parse(excluded).expect("pack parses");
        // contraction_ratio wildly out of band, but excluded; only
        // em_dash_density (inside its band) counts -> score is exactly 0.
        let metrics = metrics_with(0.0, 2.0);
        let score = pack
            .combined_score("blog", &metrics)
            .expect("em_dash_density is included");
        assert_eq!(score, 0.0);
    }

    /// A genre with no bands at all in this pack has no combined score.
    #[test]
    fn combined_score_none_for_unknown_genre() {
        let pack = EnvelopePack::parse(SAMPLE).expect("sample pack parses");
        assert_eq!(
            pack.combined_score("not_a_genre", &MetricVector::default()),
            None
        );
    }
}
