//! Property tests for the pure conflict-resolution/apply pipeline
//! (`resolve_round` + `apply_patches`): valid UTF-8 output, no overlapping
//! accepted patches, and a zero-patch no-op — over adversarial,
//! proptest-generated inputs (arbitrary byte ranges, not necessarily
//! char-boundary-safe or non-overlapping) rather than hand-picked
//! fixtures.

use friction_apply::{Candidate, apply_patches, resolve_round};
use friction_core::{Patch, RuleId, Tier, find_overlaps};
use friction_rules::RuleFamily;
use proptest::prelude::*;

/// A source string with a mix of ASCII and multi-byte UTF-8 characters, so
/// generated byte offsets have real char-boundary traps to fall into.
const fn sample_source() -> &'static str {
    "café, naïve résumé — the quick brown fox jumps over the lazy dog. 日本語もあります。"
}

/// One family per `u8 % 6`, cycling through every `RuleFamily` variant —
/// used so generated candidates exercise every conflict-resolution
/// priority tier, not just one.
const fn family_from_u8(n: u8) -> RuleFamily {
    match n % 6 {
        0 => RuleFamily::Structural,
        1 => RuleFamily::Symmetry,
        2 => RuleFamily::Connective,
        3 => RuleFamily::Lexical,
        4 => RuleFamily::Rhythm,
        _ => RuleFamily::Contraction,
    }
}

/// A strategy for one candidate patch over `len` bytes: two arbitrary
/// offsets in `0..=len` (ordered into a range, possibly empty, possibly
/// off a char boundary), a short replacement string, a rule-id-ish tag,
/// and a rule family.
fn candidate_strategy(len: usize) -> impl Strategy<Value = Candidate> {
    (0..=len, 0..=len, "[a-zA-Z]{0,4}", 0u8..6, 0u32..8).prop_map(
        move |(a, b, replacement, family_byte, rule_tag)| {
            let (start, end) = if a <= b { (a, b) } else { (b, a) };
            let rule = rule_id_for(rule_tag);
            Candidate {
                patch: Patch::new(start..end, replacement, rule, Tier::Fix),
                family: family_from_u8(family_byte),
            }
        },
    )
}

/// A small, fixed pool of `RuleId`s so `resolve_round`'s rule-id tiebreak
/// has something to actually compare across repeated proptest cases.
const fn rule_id_for(tag: u32) -> RuleId {
    const IDS: [&str; 8] = [
        "stub.a", "stub.b", "stub.c", "stub.d", "stub.e", "stub.f", "stub.g", "stub.h",
    ];
    RuleId::new(IDS[(tag as usize) % IDS.len()])
}

proptest! {
    /// `resolve_round`'s accepted patches never overlap, for arbitrary
    /// (including invalid, overlapping, off-boundary) candidates.
    #[test]
    fn accepted_patches_never_overlap(
        candidates in proptest::collection::vec(candidate_strategy(sample_source().len()), 0..12)
    ) {
        let source = sample_source();
        let (accepted, _dropped) = resolve_round(source, candidates);
        prop_assert!(find_overlaps(&accepted).is_empty());
    }

    /// Applying `resolve_round`'s accepted output always yields valid
    /// UTF-8 text (trivially guaranteed by `String`'s own invariant, but
    /// exercised end to end here rather than assumed) and never panics,
    /// for arbitrary candidates.
    #[test]
    fn applying_accepted_patches_yields_valid_utf8(
        candidates in proptest::collection::vec(candidate_strategy(sample_source().len()), 0..12)
    ) {
        let source = sample_source();
        let (accepted, _dropped) = resolve_round(source, candidates);
        let result = apply_patches(source, &accepted);
        prop_assert!(std::str::from_utf8(result.as_bytes()).is_ok());
    }

    /// Applying zero patches returns the input unchanged, byte-for-byte,
    /// for any source string proptest generates (not just the fixed
    /// sample).
    #[test]
    fn applying_zero_patches_is_a_byte_exact_no_op(source in ".{0,200}") {
        let result = apply_patches(&source, &[]);
        prop_assert_eq!(result.as_bytes(), source.as_bytes());
    }

    /// Every candidate `resolve_round` accepts was present, byte-for-byte,
    /// among the candidates it was given — resolution only ever selects a
    /// subset, never fabricates or mutates a patch.
    #[test]
    fn accepted_patches_are_a_subset_of_the_input(
        candidates in proptest::collection::vec(candidate_strategy(sample_source().len()), 0..12)
    ) {
        let source = sample_source();
        let inputs: Vec<Patch> = candidates.iter().map(|c| c.patch.clone()).collect();
        let (accepted, _dropped) = resolve_round(source, candidates);
        for patch in &accepted {
            prop_assert!(inputs.contains(patch));
        }
    }
}
